### ISSUE TITLE
problème avec token-generator.py bad request

### ISSUE THREAD

**Issue by Charlo26** [Ultchad/snips-skill-spotifywebapi#21]
Bonjour, j'ai aussi un problème avec le token generator... 
J'ai déjà un problème avec le setup.sh car il me dit ne pas trouver de hermes_python >= 0.3.1 ( ou je sais plus combien ), sauf que je l'installe manuellement la 0.4.1.

Bref, je lance le token-generator.py et j'ai une érreur lors que je met le liens généré par spotify ;
```
Traceback (most recent call last):
  File "token-generator.py", line 117, in <module>
    scope=scope, redirect_uri=redirect_uri)
  File "/var/lib/snips/skills/snips-skill-spotifywebapi/src/spotipy/spotipy/util.py", line 88, in prompt_for_user_token
    token_info = sp_oauth.get_access_token(code)
  File "/var/lib/snips/skills/snips-skill-spotifywebapi/src/spotipy/spotipy/oauth2.py", line 217, in get_access_token
    raise SpotifyOauthError(response.reason)
spotipy.oauth2.SpotifyOauthError: Bad Request
```

Je n'ai vraiment pas d'idée d'ou cela peut venir ?

Merci d'avance !

**Comment by Ultchad** [comment]
Peux tu me donner le résultat de ces commandes

```bash
pwd # Position actuelle dans le systeme de fichier
git rev-parse --abbrev-ref HEAD # Nom de la branch git sur la quel tu est
which python # L'emplacement du python utilisé
python --version # Version du python utilisé
pip freeze # Version des modules python utilisé
```

**Comment by Charlo26** [comment]
Bonjour Ultchad, alors pour faire simple j'ai remis mon RPi à zéro, je suis reparti d'une installation fraiche, et tout fonctionne. Cela faisait des mois que je bidouillais dessus à installer et désinstaller des paquets... Et au bout d'un moment ça devient trop le bazar..

Merci pour ta réponse et désolé pour le dérangement !
