### ISSUE TITLE
impossible de lire un son après installation

### ISSUE THREAD

**Issue by nbabble** [Ultchad/snips-skill-spotifywebapi#24]
Bonjour,

tout d'abord merci d'avoir créé cette API. ca s'annonce top même si je recontre actuellement des difficultés pour tout faire fonctionner.

lorsque je demande à SNIPS de lancer une musique, j'ai l'erreur suivante : "Désolé une erreur c'est produite: Aucun équipement actif n'a été trouvé" avez vous une idée ?
Par équipement j'imagine que ca peut être les navigateurs web ? J'ai donc essayé de lancer le web player de spotify sur chromium et firefox en vain... 
j'utilise Raspbian Stretch sur RPI 3b+. 

Merci d'avance pour votre aide.

**Comment by Ultchad** [comment]
Je n'ai jamais testé avec un client Web, les équipement que testé sont: le téléphone, le cast sur diferent appareil et l'application spotify pour ordinateur 

Cette application communique, via internet, avec spotify pour contrôler votre lecture en cours 

Pouvez-vous tester un de ces équipements ? Je verrai à faire le test de mon côté dès que j'ai le temps

**Comment by nbabble** [comment]
Bonjour,

Tout d'abord je n'avais pas compris le fonctionnement de l'API (contrôler spotify sur un appareil déjà lancé). Je pensais qu'elle permettait de lancer spotify sur le raspberry via le web player.
Maintenant que mon incomprehension est corrigée, je confirme que l'API fonctionne très bien.
MERCI pour cette superbe API ! 
Concernant le webplayer chromium, je me pencherai dessus plus tard. 
Il ne me reste plus qu'à réussir à me faire comprendre de snips lorsque je lui demande un groupe au nom anglophone ^^'
A+ Nico.
