### ISSUE TITLE
help on execution of token-generator.py

### ISSUE THREAD

**Issue by felinh** [Ultchad/snips-skill-spotifywebapi#3]
Hi 
First, thank you and congrats for that nice idea. 

I have a problem to get the token.
the code is installed on a RPI with no WEB browser. 
on execution of token-generator.py, it is asked to pastean url to complete the authorization.
I don't have browser on the RPI, so I did copied it on my PC browser (that has nothing to do with my PI), and the error return ERR_CONNECTION_REFUSED.

my setting  in conf.ini :redirect_uri=http://localhost/
and on spotify side:
![image](https://user-images.githubusercontent.com/38888761/50057551-2e83dc00-016c-11e9-80c8-1655f257796e.png)

what could be wrong?
Thank you very much

**Comment by Ultchad** [comment]
Have you an adblock on your browser ?
Many people have this error, resolve it by remove adblock  

If it's not work :
When have you this error ? 
Juste after paste the URL on your browser ? Or after allows the app on spotify page ?

**Comment by felinh** [comment]
> Juste after paste the URL on your browser ?

just after the paste

**Comment by Ultchad** [comment]
You are already connect to your spotify account on your browser ?
Normally, before check if request uri is valid (client I'd,secret and redirect ), spotify open the page of account connection, after you accept the app and after you redirect to your uri 
Example for redirect http://localhost/

http://localhost/code=YOUR_TOKEN 

and you copy this full url in the command 

Can you try in other browsers or in privacy mode ? Without connection with your spotify account and no adblock

**Comment by felinh** [comment]
Hello
I did put http://localhost:8888 and created & run a app.js server on my PC (as explained in the [spotify git](https://github.com/spotify/web-api-auth-examples)).  It completed the authorization, with the authorization page as expected.  
Started to play with your snips apps now! Great thank you
