### ISSUE TITLE
Choix player

### ISSUE THREAD

**Issue by Hydro8** [Ultchad/snips-skill-spotifywebapi#4]
Salut
Je suis très intéressé par ce skill. Comment choisir sur quel lecteur la musique sera jouée ?

Par exemple si dans Spotify connect j'ai Salon et chambre, dois je spécifier le lecteur à chaque fois ?

Merci

**Comment by Ultchad** [comment]
Pour l'instant ce skill permet de commander un device que si il est relié au compte que tu a lié à l'app. 
Ce skill passe par la web api de spotify qui ne permet pas à ma connaissance de voir les device disponible comme sur ton téléphone, il ne voie que les device au quel tu est connecté, 
Donc tu doit t'y connecter et ensuite Snips pourra le contrôler
J'essayerai de voir si cette limitation peux etre contourné ou améliorer 

Si je ne me suis pas fait comprendre ou si je n'est pas répondu à ta question n'hésite pas à me le dire, je laisse cette issue ouverte tu n'auras qu'à la fermer quand tu veux 
Si tu a des idée, ou envie d'amélioration n'hésite pas aussi, via une autres issue

**Comment by Ultchad** [comment]
Pas de réponse je clôture, tu pourras réouvrir cet incident si nécessaire
