### ISSUE TITLE
redirect URI

### ISSUE THREAD

**Issue by richardpub4136** [Ultchad/snips-skill-spotifywebapi#7]
A quoi correspond le redirect URI

**Comment by richardpub4136** [comment]
Désolé je viens de voir (exemple: ' http: // localhost / ' est la valeur par défaut de cette application)

**Comment by Ultchad** [comment]
Tu doit créé une application sur la page des devloper de spotify, et tu doit indiqué l'uri de redirection dessus 

Quand tu générera ton token spotify va te demander si tu authorise cette Application à accéder à ton compte et si tu accepte il renverra le token sur l'uri indiqué 

Tu peux y mette http://localhost/ spotify te renverra dessus, localhost correspond à ton pc, donc à moins que tu héberge dessus un site il te dira page non trou

Mais pas de soucis tu copies l'url  qui est dans ta bar d'adresse et qui contient le token et tu la colle comme demandé à la suite du script 

Je suis parti plus loin que t'a question mais j'espère avoir été clair et surtout d'y avoir répondu

**Comment by richardpub4136** [comment]
Merci pour ta réponse, très claire
A plus
